
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class for_pass extends javax.swing.JFrame {
    Connection conn;
    PreparedStatement ps;
    ResultSet rs;
    
    
    /**
     * Creates new form for_pass
     */
    public for_pass() {
        initComponents();
        conn=connectiondb.db();
        super.setTitle("Library Management System-FORGOT PASSWORD");
        ImageIcon in=new ImageIcon("Assets\\icon.png");
        super.setIconImage(in.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 51, 102));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setAutoscrolls(false);
        jTextField1.setBorder(null);
        jTextField1.setOpaque(false);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 430, 40));

        jTextField2.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 102, 102));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setAutoscrolls(false);
        jTextField2.setBorder(null);
        jTextField2.setDisabledTextColor(new java.awt.Color(255, 102, 102));
        jTextField2.setEnabled(false);
        jTextField2.setOpaque(false);
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 430, 40));

        jTextField3.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 102, 102));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setAutoscrolls(false);
        jTextField3.setBorder(null);
        jTextField3.setDisabledTextColor(new java.awt.Color(255, 102, 102));
        jTextField3.setEnabled(false);
        jTextField3.setOpaque(false);
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 365, 430, 40));

        jTextField4.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 51, 102));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setAutoscrolls(false);
        jTextField4.setBorder(null);
        jTextField4.setOpaque(false);
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, 430, 40));

        jButton1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 0, 153));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/search.png"))); // NOI18N
        jButton1.setText("Search");
        jButton1.setAlignmentY(0.0F);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 250, -1, 40));

        jButton3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 102, 102));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/retrive.png"))); // NOI18N
        jButton3.setText("Retrive");
        jButton3.setAlignmentY(0.0F);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton3KeyReleased(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 570, -1, 40));

        jButton2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 102, 102));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/back.png"))); // NOI18N
        jButton2.setText("Back");
        jButton2.setAlignmentY(0.0F);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton2KeyReleased(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 570, 130, 40));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 220, 140, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/for_pass.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        int c= evt.getKeyCode();
        if(c==KeyEvent.VK_ENTER)
        {
            if(jTextField1.getText().equals(""))
                jTextField4.requestFocus();
            else
                jButton1.doClick();
        }
        if(c==KeyEvent.VK_DOWN)
        {
            if(jTextField1.getText().equals(""))
                jTextField4.requestFocus();
            else
                jButton1.doClick();
        }
        if(c==KeyEvent.VK_UP)
        {
            jButton2.requestFocus();
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased
        int c= evt.getKeyCode();
        if(c==KeyEvent.VK_ENTER)
        {
            jButton3.doClick();
        }
        if(c==KeyEvent.VK_DOWN)
        {
            jButton3.requestFocus();
        }
        if(c==KeyEvent.VK_UP)
        {
            jTextField1.requestFocus();
        }
    }//GEN-LAST:event_jTextField4KeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Login ln=new Login();
        ln.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyReleased
        int c= evt.getKeyCode();
        if(c==KeyEvent.VK_UP)
        {
            jButton3.requestFocus();
        }
        if(c==KeyEvent.VK_DOWN)
        {
            jTextField1.requestFocus();
        }
    }//GEN-LAST:event_jButton2KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    if(jTextField1.getText().equals(""))
    {
        JOptionPane.showMessageDialog(rootPane, "Please Fill The Username");
    }
    else
    {
        String asql ="Select name,seq_q From user_reg  Where username=?";
        try 
        {
            ps=conn.prepareStatement(asql);
            ps.setString(1, jTextField1.getText());
            rs=ps.executeQuery();
            if(rs.next())
            {
                jTextField2.setText(rs.getString(1));
                jTextField3.setText(rs.getString(2));
                ImageIcon icon = new ImageIcon("Assets\\verify.png");
                jLabel3.setIcon(icon);
                jTextField4.requestFocus();
            }
            else
            {
                jLabel3.setIcon(null);
                JOptionPane.showMessageDialog(rootPane, "No Such Username Found in the Database");
                jTextField1.requestFocus();
            }
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(for_pass.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally
        {
            try 
            {
                rs.close();
                ps.close();
                jTextField4.requestFocus();
            } 
            catch (SQLException ex) 
            {
                Logger.getLogger(User_reg.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    if(jTextField1.getText().equals("")||jTextField4.getText().equals(""))
    {
        JOptionPane.showMessageDialog(rootPane, "Please Complete Your Details");
    }
    else
    {    
        String asql ="Select username,password from user_reg Where seq_q=? and answer=?";
        try {
            ps=conn.prepareStatement(asql);
            ps.setString(1, jTextField3.getText());
            ps.setString(2, jTextField4.getText());
            rs=ps.executeQuery();
            if(rs.next())
            {
                String usn,pass;
                usn=rs.getString(1);
                pass=rs.getString(2);
                JOptionPane.showMessageDialog(rootPane, "Your Username and Password\nUsername: "+usn+"\nPassword: "+pass, "Retrived Password", HEIGHT);
                Login ln=new Login();
                ln.jTextField1.setText(usn);
                ln.jPasswordField1.setText(pass);
                ln.jPasswordField1.requestFocus();
                ln.setVisible(true);
                this.dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Answer is Wrong");
                jTextField4.requestFocus();
            }
        } catch (SQLException ex) {
            Logger.getLogger(for_pass.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            try {
                rs.close();
                ps.close();
                jTextField4.requestFocus();
                
            } catch (SQLException ex) {
                Logger.getLogger(User_reg.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyReleased
        int c= evt.getKeyCode();
        if(c==KeyEvent.VK_UP)
        {
            jTextField4.requestFocus();
        }
        if(c==KeyEvent.VK_DOWN)
        {
            jButton2.requestFocus();
        }
    }//GEN-LAST:event_jButton3KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(for_pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(for_pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(for_pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(for_pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new for_pass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
