

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.*;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class issue_book extends javax.swing.JFrame {

Connection conn;
PreparedStatement ps;
ResultSet rs;
int quan;
    /**
     * Creates new form issue_book
     */
    public issue_book() {
        initComponents();
        conn=connectiondb.db();
        date();
        super.setTitle("Library Management System-Issue Book");
        ImageIcon im =new ImageIcon("Assets//icon.png");
        super.setIconImage(im.getImage());
        showdate();
    }

        public void showdate()
    {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d=new Date();
                SimpleDateFormat s= new SimpleDateFormat("dd/MM/yyyy");
                SimpleDateFormat s1= new SimpleDateFormat("hh:mm:ss");
                jLabel18.setText("Date : "+s.format(d)+"    Time: " +s1.format(d));
            }
        }).start();
    }

    public void date()
    {
        Date d= jDateChooser2.getDate();
        Calendar c=Calendar.getInstance();
        try {
            c.setTime(d);
        } catch (Exception e) {
        }
        c.add(Calendar.DAY_OF_MONTH, 7);
        jDateChooser1.setDate(c.getTime());
    }
    
    public void searchdet(String ref)
    {
        try {
            String s="Select quantity from add_book where bookid=?";
            ps=conn.prepareStatement(s);
            ps.setString(1, ref);
            rs=ps.executeQuery();
            rs.next();
            if(Integer.parseInt(rs.getString(1))==0)
                quan=Integer.parseInt(rs.getString(1));
            else
                quan=Integer.parseInt(rs.getString(1))-1;
            System.err.println(quan);
        } catch (Exception e) {
        }
        finally
        {
            try {
                rs.close();
                ps.close();
            } catch (Exception e) {
            }
        }
    }
    public void return_book(String ref)
    {
        try {
            String s="UPDATE add_book SET quantity="+quan+" where bookid=?";
            ps=conn.prepareStatement(s);
            ps.setString(1, ref);
            ps.executeUpdate();
            quan=0;
        } catch (Exception e) {
        }
        finally
        {
            try {
                rs.close();
                ps.close();
            } catch (Exception e) {
            }
        }
    }
    public int verify(String bookid,String studntid)
    {
        int i=0;
        String url="Select bookname from issue_book where bookid=? and studntid=?";
            try {
                ps=conn.prepareStatement(url);
                ps.setString(1, bookid);
                ps.setString(2, studntid);
                rs=ps.executeQuery();
                if(rs.next())
                {
                    jButton6.doClick();
                    JOptionPane.showMessageDialog(rootPane, "Book with this "+bookid+" Book Id Already Issued to same Student with Id "+studntid);
                    
                }
                else
                    i=1;
            } catch (Exception e) {
            }
            finally
            {
                try {
                    rs.close();
                    ps.close();
                } catch (Exception e) {
                }
            }
        return i;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDateChooser1.setDate(new Date());
        jDateChooser1.setDateFormatString("dd/MM/yyyy");
        jDateChooser1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jDateChooser1.setOpaque(false);
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 373, 190, 35));

        jDateChooser2.setDate(new Date());
        jDateChooser2.setDateFormatString("dd/MM/yyyy");
        jDateChooser2.setEnabled(false);
        jDateChooser2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jDateChooser2.setOpaque(false);
        getContentPane().add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 373, 190, 35));

        jButton2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/SEO-icon-1.png"))); // NOI18N
        jButton2.setText("Search Book");
        jButton2.setFocusPainted(false);
        jButton2.setIconTextGap(5);
        jButton2.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 130, 30));

        jButton3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/SEO-icon-1.png"))); // NOI18N
        jButton3.setText("Search Book");
        jButton3.setFocusPainted(false);
        jButton3.setIconTextGap(5);
        jButton3.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 320, 130, 30));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 40, 30));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 180, 40, 30));

        jTextField1.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 102, 102));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setAutoscrolls(false);
        jTextField1.setBorder(null);
        jTextField1.setOpaque(false);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 176, 300, 32));

        jTextField2.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 102, 102));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setAutoscrolls(false);
        jTextField2.setBorder(null);
        jTextField2.setEnabled(false);
        jTextField2.setOpaque(false);
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 225, 300, 30));

        jTextField3.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 102, 102));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setAutoscrolls(false);
        jTextField3.setBorder(null);
        jTextField3.setEnabled(false);
        jTextField3.setOpaque(false);
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 272, 300, 30));

        jTextField4.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 102, 102));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setAutoscrolls(false);
        jTextField4.setBorder(null);
        jTextField4.setOpaque(false);
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 305, 30));

        jTextField5.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 102, 102));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setAutoscrolls(false);
        jTextField5.setBorder(null);
        jTextField5.setEnabled(false);
        jTextField5.setOpaque(false);
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 305, 30));

        jTextField6.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(255, 102, 102));
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setAutoscrolls(false);
        jTextField6.setBorder(null);
        jTextField6.setEnabled(false);
        jTextField6.setOpaque(false);
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 278, 305, 30));

        jButton1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 0, 153));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/issue-book (2).png"))); // NOI18N
        jButton1.setText("Issue Book");
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, 210, 40));

        jRadioButton1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(102, 0, 102));
        jRadioButton1.setText("Enable");
        jRadioButton1.setFocusPainted(false);
        jRadioButton1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jRadioButton1.setOpaque(false);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 345, -1, -1));

        jLabel18.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 51, 153));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 120, 420, 20));

        jButton6.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/icons8-trash-48.png"))); // NOI18N
        jButton6.setText("Clear");
        jButton6.setFocusPainted(false);
        jButton6.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 500, 130, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/issue_book.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextField5.setText("");
        jTextField6.setText("");
        if(jTextField4.getText().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Please fill Book Id");
        }
        else
        {
            String url="Select bookname,edition,quantity from add_book where bookid=?";
            try {
                ps=conn.prepareStatement(url);
                ps.setString(1, jTextField4.getText());
                rs=ps.executeQuery();
                if(rs.next())
                {
                    if(rs.getInt(3)==0)
                    {
                        JOptionPane.showMessageDialog(rootPane, "The Book is Out of Stock Registerd with Book Id: "+jTextField4.getText());
                    }
                    else
                    {
                        jTextField5.setText(rs.getString(1));
                        jTextField6.setText(rs.getString(2));
                        ImageIcon icon=new ImageIcon("Assets\\verify.png");
                        jLabel4.setIcon(icon); 
                    }

                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, "No Book Registered with this Book ID: "+jTextField4.getText()+" or it is Out of Stock");
                    jLabel4.setIcon(null);
                }
            } catch (Exception e) {
            }
            finally
            {
                try {
                    rs.close();
                    ps.close();
                } catch (Exception e) {
                }
            }
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jTextField2.setText("");
        jTextField3.setText("");
        if(jTextField1.getText().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Please fill Student Id");
        }
        else
        {
            String url="Select sname,course from add_student where studentid=?";
            try {
                ps=conn.prepareStatement(url);
                ps.setString(1, jTextField1.getText());
                rs=ps.executeQuery();
                if(rs.next())
                {
                    jTextField2.setText(rs.getString(1));
                    jTextField3.setText(rs.getString(2));
                    ImageIcon icon=new ImageIcon("Assets\\verify.png");
                    jLabel3.setIcon(icon);

                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, "No Student Registered with this Student ID: "+jTextField1.getText());
                    jLabel3.setIcon(null);
                }
            } catch (Exception e) {
            }
            finally
            {
                try {
                    rs.close();
                    ps.close();
                } catch (Exception e) {
                }
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        int c= evt.getKeyCode();
        if(c==KeyEvent.VK_ENTER)
        {
            jButton3.doClick();
            jDateChooser1.requestFocus();
        }
        if(c==KeyEvent.VK_DOWN)
        {
            jButton3.doClick();
            jDateChooser1.requestFocus();
            
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased
        int c= evt.getKeyCode();
        if(c==KeyEvent.VK_ENTER)
        {
            jButton2.doClick();
            jTextField1.requestFocus();
        }
        if(c==KeyEvent.VK_DOWN)
        {
            jButton2.doClick();
            jTextField1.requestFocus();
        }
    }//GEN-LAST:event_jTextField4KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(jTextField1.getText().equals("")||jTextField2.getText().equals("")||jTextField3.getText().equals("")||jTextField4.getText().equals("")||jTextField5.getText().equals("")||jTextField6.getText().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Please Fill The Empty Fields");
        }
        else
        {
            int i=verify(jTextField4.getText(), jTextField1.getText());
            if(i==1)
            {
                try {
                
                    String url="insert into issue_book (bookid,bookname,edition,studntid,sname,course,issuedate,returndate) values(?,?,?,?,?,?,?,?)";
                    searchdet(jTextField4.getText());
                    return_book(jTextField4.getText());
                    ps=conn.prepareStatement(url);
                    ps.setString(1, jTextField4.getText());
                    ps.setString(2, jTextField5.getText());
                    ps.setString(3, jTextField6.getText());
                    ps.setString(4, jTextField1.getText());
                    ps.setString(5, jTextField2.getText());
                    ps.setString(6, jTextField3.getText());
                    Date d=jDateChooser2.getDate();
                    Date d2=jDateChooser1.getDate();
                    ps.setString(7, new SimpleDateFormat("dd/MM/yyyy").format(d));
                    ps.setString(8, new SimpleDateFormat("dd/MM/yyyy").format(d2));
                    ps.execute();
                    JOptionPane.showMessageDialog(rootPane, "Book Name "+jTextField5.getText()+" Issued to "+jTextField2.getText());
                    jTextField1.setText("");
                    jTextField2.setText("");
                    jTextField3.setText("");
                    jTextField4.setText("");
                    jTextField5.setText("");
                    jTextField6.setText("");
                    jLabel3.setIcon(null);
                    jLabel4.setIcon(null);
                } catch (Exception e) {
                    System.out.println(e);
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        if(jRadioButton1.isSelected())
        {
            jDateChooser2.setEnabled(true);
        }
        else jDateChooser2.setEnabled(false);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField4.requestFocus();
        jDateChooser2.setEnabled(false);
        jRadioButton1.setSelected(false);
        jLabel3.setIcon(null);
        jLabel4.setIcon(null);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(issue_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(issue_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(issue_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(issue_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new issue_book().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
