
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class preloader extends javax.swing.JFrame {

    Connection conn;
    ResultSet rs;
    PreparedStatement ps;
    /**
     * Creates new form preloader
     */
    public preloader() {
        initComponents();
        conn=connectiondb.db();
        super.setTitle("Loading....");
        ImageIcon in=new ImageIcon("Assets\\icon.png");
        super.setIconImage(in.getImage());
        if(conn==null)
            System.exit(0);
        
    }
    
    
    public void load() throws SQLException
    {
        
        int user_c,lib_c;
        String url="SELECT COUNT(*) FROM lib_reg";
        ps=conn.prepareStatement(url);
        rs=ps.executeQuery();
        rs.next();
        lib_c=rs.getInt(1);
        rs.close();
        ps.close();
        if (lib_c==0)
        {
            lib_register lr =new lib_register();
            lr.setVisible(true);
        }
        else
        {
            url="SELECT COUNT(*) FROM user_reg";
            ps=conn.prepareStatement(url);
            rs=ps.executeQuery();
            rs.next();
            user_c=rs.getInt(1);
            rs.close();
            ps.close();
            if(user_c==0)
            {
                User_reg Ur =new User_reg();
                Ur.jButton2.setVisible(false);
                Ur.jButton5.setVisible(false);
                Ur.setVisible(true);
            }
            else
            {
                Login ln= new Login();
                ln.setVisible(true);
            }
        }
        
            
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar2 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jProgressBar2.setBackground(new java.awt.Color(255, 255, 255));
        jProgressBar2.setValue(50);
        jProgressBar2.setAlignmentX(0.0F);
        jProgressBar2.setAlignmentY(0.0F);
        jProgressBar2.setBorderPainted(false);
        jProgressBar2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jProgressBar2.setFocusable(false);
        getContentPane().add(jProgressBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 541, 530, 10));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("0%");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, 40, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Loading......");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/red login form.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws SQLException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(preloader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(preloader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(preloader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(preloader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        preloader sp = new preloader();
        sp.setVisible(true);
        try {
            for(int i=0;i<=100;i++)
            {
                Thread.sleep(30);
                jLabel2.setText(i+" %");
                sp.jProgressBar2.setValue(i);
                if(i==10)
                {
                    jLabel3.setText("Turning on Modules.....");
                }
                if(i==30)
                {
                    jLabel3.setText("Loading Modules.....");
                }
                if(i==60)
                {
                    jLabel3.setText("Connecting to Database.....");
                }
                if(i==90)
                {
                    jLabel3.setText("Launching Application.....");
                }
            }
        } catch (InterruptedException e) {
        }
        if(jProgressBar2.getValue()==100)
        {
            sp.load();
            
            sp.setVisible(false);
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private static javax.swing.JLabel jLabel2;
    private static javax.swing.JLabel jLabel3;
    private static javax.swing.JProgressBar jProgressBar2;
    // End of variables declaration//GEN-END:variables
}
