
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class User_reg extends javax.swing.JFrame {

    Connection conn;
    ResultSet rs;
    PreparedStatement ps;
    /**
     * Creates new form User_reg
     */
    public User_reg() {
        initComponents();
        conn=connectiondb.db();
        super.setTitle("Library Management System-USER REGISTER");
        ImageIcon in=new ImageIcon("Assets\\icon.png");
        super.setIconImage(in.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 102, 102));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/submit.png"))); // NOI18N
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton2KeyReleased(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 580, 150, 40));

        jButton3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 102, 102));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/next.png"))); // NOI18N
        jButton3.setText("Next");
        jButton3.setEnabled(false);
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 580, 130, 40));

        jButton5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 102, 102));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/submit.png"))); // NOI18N
        jButton5.setText("Submit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton5KeyReleased(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 580, 150, 40));

        jButton4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 102, 102));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/submit.png"))); // NOI18N
        jButton4.setText("Submit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton4KeyReleased(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 580, 150, 40));

        jTextField5.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 102, 102));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setAutoscrolls(false);
        jTextField5.setBorder(null);
        jTextField5.setOpaque(false);
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField5KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 480, 430, 40));

        jTextField4.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 102, 102));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setAutoscrolls(false);
        jTextField4.setBorder(null);
        jTextField4.setOpaque(false);
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, 430, 40));

        jTextField3.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 102, 102));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setAutoscrolls(false);
        jTextField3.setBorder(null);
        jTextField3.setOpaque(false);
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 365, 430, 40));

        jTextField2.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 102, 102));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setAutoscrolls(false);
        jTextField2.setBorder(null);
        jTextField2.setOpaque(false);
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 430, 40));

        jTextField1.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 102, 102));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setAutoscrolls(false);
        jTextField1.setBorder(null);
        jTextField1.setOpaque(false);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 430, 40));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 51));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 310, 140, 40));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/user_reg.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         if(jTextField1.getText().equals("")||jTextField2.getText().equals("")||jTextField3.getText().equals("")||jTextField4.getText().equals("")||jTextField5.getText().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Please Compelete Your Information");
        }
        else
        {
            try 
            {
                String sql="INSERT INTO user_reg (username,name,password,seq_q,answer) Values (?,?,?,?,?)";
                ps=conn.prepareStatement(sql);
                ps.setString(1, jTextField2.getText());
                ps.setString(2, jTextField1.getText());
                ps.setString(3, jTextField3.getText());
                ps.setString(4, jTextField4.getText());
                ps.setString(5, jTextField5.getText());
                ps.executeUpdate();
                ps.close();
                JOptionPane.showMessageDialog(rootPane, "Account Created Succefully");
                dashboard l =new dashboard();
                this.dispose();  
            } catch (HeadlessException | SQLException e) 
            {
                String em=e.getMessage();
                System.err.println(em);
                if(em.equals("[SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: user_reg.username)")) {
                    JOptionPane.showMessageDialog(rootPane, "Account Already Exists with this UserName Please Try Other UserName");
                } else JOptionPane.showMessageDialog(rootPane, e);
            }
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        try 
        {
            String asql ="Select username From user_reg  Where username=?";
            ps=conn.prepareStatement(asql);
            ps.setString(1, jTextField2.getText());
            rs=ps.executeQuery();
        }
        catch (SQLException ex) 
        {
            Logger.getLogger(User_reg.class.getName()).log(Level.SEVERE, null, ex);
        }
        int c= evt.getKeyCode();
        if(c==KeyEvent.VK_ENTER)
        {
            try {
                if(rs.next())
                {
                    JOptionPane.showMessageDialog(rootPane, "Username Already Taken");
                }
                else
                {   
                    if(!jTextField2.getText().equals(""))
                    {
                        ImageIcon im =new ImageIcon("Assets\\verify.png");
                        jLabel3.setIcon(im);
                    }
                    jTextField3.requestFocus();
                }
            } catch (SQLException ex) {
                Logger.getLogger(User_reg.class.getName()).log(Level.SEVERE, null, ex);
            }finally{

                try {
                    rs.close();
                    ps.close();
                } catch (SQLException ex) {
                    Logger.getLogger(User_reg.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        if(c==KeyEvent.VK_DOWN)
        {
            try {
                if(rs.next())
                {
                    JOptionPane.showMessageDialog(rootPane, "Username Already Taken");
                }
                else
                {   
                    if(!jTextField2.getText().equals(""))
                    {
                        ImageIcon im =new ImageIcon("Assets\\verify.png");
                        jLabel3.setIcon(im);
                    }
                    jTextField3.requestFocus();
                }
            } catch (SQLException ex) {
                Logger.getLogger(User_reg.class.getName()).log(Level.SEVERE, null, ex);
            }finally{

                try {
                    rs.close();
                    ps.close();
                } catch (SQLException ex) {
                    Logger.getLogger(User_reg.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        if(c==KeyEvent.VK_UP)
        {
            jTextField1.requestFocus();
        }
    }//GEN-LAST:event_jTextField2KeyReleased

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        int c= evt.getKeyCode();
        if(c==KeyEvent.VK_ENTER)
        {
            jTextField2.requestFocus();
        }
        if(c==KeyEvent.VK_DOWN)
        {
            jTextField2.requestFocus();
        }
        if(c==KeyEvent.VK_UP)
        {
            if(jButton2.isVisible())
                jButton2.requestFocus();
            else if(jButton5.isVisible())
                jButton5.requestFocus();
            else
                jButton4.requestFocus();
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
         int c= evt.getKeyCode();
        if(c==KeyEvent.VK_ENTER)
        {
            jTextField4.requestFocus();
        }
        if(c==KeyEvent.VK_DOWN)
        {
            jTextField4.requestFocus();
        }
        if(c==KeyEvent.VK_UP)
        {
            jTextField2.requestFocus();
        }
    }//GEN-LAST:event_jTextField3KeyReleased

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased
        int c= evt.getKeyCode();
        if(c==KeyEvent.VK_ENTER)
        {
            jTextField5.requestFocus();
        }
        if(c==KeyEvent.VK_DOWN)
        {
            jTextField5.requestFocus();
        }
        if(c==KeyEvent.VK_UP)
        {
            jTextField3.requestFocus();
        }
    }//GEN-LAST:event_jTextField4KeyReleased

    private void jTextField5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyReleased
        int c= evt.getKeyCode();
        if(c==KeyEvent.VK_ENTER)
        {
            if(jButton2.isVisible())
                jButton2.doClick();
            else if(jButton5.isVisible())
                jButton5.doClick();
            else
                jButton4.doClick();
        }
        if(c==KeyEvent.VK_DOWN)
        {
            if(jButton2.isVisible())
                jButton2.requestFocus();
            else if(jButton5.isVisible())
                jButton5.requestFocus();
            else
                jButton4.requestFocus();
        }
        if(c==KeyEvent.VK_UP)
        {
            jTextField4.requestFocus();
        }
    }//GEN-LAST:event_jTextField5KeyReleased

    private void jButton2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyReleased
        int c= evt.getKeyCode();
        if(c==KeyEvent.VK_UP)
        {
            jTextField5.requestFocus();
        }
        if(c==KeyEvent.VK_DOWN)
        {
            jTextField1.requestFocus();
        }
    }//GEN-LAST:event_jButton2KeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(jTextField1.getText().equals("")||jTextField2.getText().equals("")||jTextField3.getText().equals("")||jTextField4.getText().equals("")||jTextField5.getText().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Please Compelete Your Information");
        }
        else
        {
            try 
            {
                String sql="INSERT INTO user_reg (username,name,password,seq_q,answer) Values (?,?,?,?,?)";
                ps=conn.prepareStatement(sql);
                ps.setString(1, jTextField2.getText());
                ps.setString(2, jTextField1.getText());
                ps.setString(3, jTextField3.getText());
                ps.setString(4, jTextField4.getText());
                ps.setString(5, jTextField5.getText());
                ps.executeUpdate();
                ps.close();
                JOptionPane.showMessageDialog(rootPane, "Account Created Succefully");
                Login l =new Login();
                l.jTextField1.setText(jTextField2.getText());
                l.setVisible(true);
                this.dispose();  
            } catch (HeadlessException | SQLException e) 
            {
                String em=e.getMessage();
                System.err.println(em);
                if(em.equals("[SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: user_reg.username)")) {
                    JOptionPane.showMessageDialog(rootPane, "Account Already Exists with this UserName Please Try Other UserName");
                } else JOptionPane.showMessageDialog(rootPane, e);
            }
            
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton4KeyReleased
        int c= evt.getKeyCode();
        if(c==KeyEvent.VK_UP)
        {
            jTextField5.requestFocus();
        }
        if(c==KeyEvent.VK_DOWN)
        {
            jTextField1.requestFocus();
        }
    }//GEN-LAST:event_jButton4KeyReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(jTextField1.getText().equals("")||jTextField2.getText().equals("")||jTextField3.getText().equals("")||jTextField4.getText().equals("")||jTextField5.getText().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Please Compelete Your Information");
        }
        else
        {
            try 
            {
                String sql="INSERT INTO user_reg (username,name,password,seq_q,answer) Values (?,?,?,?,?)";
                ps=conn.prepareStatement(sql);
                ps.setString(1, jTextField2.getText());
                ps.setString(2, jTextField1.getText());
                ps.setString(3, jTextField3.getText());
                ps.setString(4, jTextField4.getText());
                ps.setString(5, jTextField5.getText());
                ps.executeUpdate();
                ps.close();
                JOptionPane.showMessageDialog(rootPane, "Account Created Succefully");
                Login l =new Login();
                l.jTextField1.setText(jTextField2.getText());
                l.setVisible(true);
                this.dispose();  
            } catch (HeadlessException | SQLException e) 
            {
                String em=e.getMessage();
                System.err.println(em);
                if(em.equals("[SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: user_reg.username)")) {
                    JOptionPane.showMessageDialog(rootPane, "Account Already Exists with this UserName Please Try Other UserName");
                } else JOptionPane.showMessageDialog(null, e);
            }
            
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton5KeyReleased
        int c= evt.getKeyCode();
        if(c==KeyEvent.VK_UP)
        {
            jTextField5.requestFocus();
        }
        if(c==KeyEvent.VK_DOWN)
        {
            jTextField1.requestFocus();
        }
    }//GEN-LAST:event_jButton5KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_reg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    public javax.swing.JButton jButton4;
    public javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
